[package]
name = "sheepstor"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4.27"
clap = { version = "4.5.41", features = ["derive"] }
flexi_logger = { version = "0.31.2", features = ["colors"] }