source_root: /opt/data/sheepstor_rust/data/sources
docs_root: /opt/data/sheepstor_rust/data/docs
github_webhook_secret_env_key: ANTLEAF_K8S_GITHUB_WEBHOOK_SECRET
websites:
  - id: "repo_for_testing_webhooks"
    processor_root: 'webroot'
    content_processor: 'hugo'
    index: false
    git:
      clone_id: "git@github.com:antleaf/repo_for_testing_webhooks.git"
      repo_name: 'antleaf/repo_for_testing_webhooks'
      branch: 'development'
#  - id: "www.antleaf.com"
#    processor_root: 'webroot'
#    content_processor: 'hugo'
#    index: false
#    git:
#      clone_id: "git@github.com:antleaf/www.antleaf.com.git"
#      repo_name: 'antleaf/www.antleaf.com'
#      branch: 'master'
#  - id: "coar-notify.net"
#    processor_root: 'webroot'
#    content_processor: 'hugo'
#    index: true
#    git:
#      clone_id: "git@github.com:coar-notify/coar-notify.net.git"
#      repo_name: 'coar-notify/coar-notify.net'
#      branch: 'main'
#  - id: "repo_for_testing_webhooks"
#    processor_root: 'webroot'
#    content_processor: 'hugo'
#    index: false
#    git:
#      clone_id: "git@github.com:antleaf/repo_for_testing_webhooks.git"
#      repo_name: 'antleaf/repo_for_testing_webhooks'
#      branch: 'development'